#Local development environment.
spring:
  application:
    name: instructor-eureka-center

server:
  port: 8000
  tomcat:
    max-threads: 800      #tomcat max threads,default is 200.
    uri-encoding: UTF-8

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000
  client:
    register-with-eureka: false #是否将自己注册到Eureka Server,默认为true.
    fetch-registry: false  #是否从Eureka Server获取注册信息，默认为true. 单点不需要。


